# Generated by Django 3.0.3 on 2020-05-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200530_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='quote',
        ),
    ]
